
name: CI

on:
  push:
    branches: [ main, 1.15 ]
  pull_request:
    branches: [ main, 1.15 ]

env:
  mvn_options: --batch-mode -Dstyle.color=always -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS

jobs:
  build:
    strategy:
      matrix:
        java-version: [ 11 ]
        runs-on: [ ubuntu-latest, macos-latest, windows-latest ]
    name: Build on ${{ matrix.runs-on }} with jdk ${{ matrix.java-version }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        env:
          SLACK_FOR_FLINK_BOT_TOKEN: ${{ secrets.SLACK_FOR_FLINK_BOT_TOKEN }}
          SLACK_FOR_FLINK_CHANNEL_ID: ${{ secrets.SLACK_FOR_FLINK_CHANNEL_ID }}
        run: ./mvnw $mvn_options package --file pom.xml
